--INSERT INTO CHORES (TITLE) VALUES ('CLEANING');


DROP TABLE IF EXISTS CHORES;

CREATE TABLE CHORES (
  CHORE_ID INT AUTO_INCREMENT  PRIMARY KEY,
  TITLE VARCHAR(64) NOT NULL,
  TIME_CREATED TIMESTAMP,
  TIME_UPDATED TIMESTAMP,
  TIME_DELETED TIMESTAMP
);

INSERT INTO CHORES (TITLE) VALUES
  ('Mopping'),
  ('Cleaning'),
  ('Laundry'),
  ('Shopping');